-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 19:50:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `CPF` VARCHAR(11) NULL,
  `Telefone` VARCHAR(12) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Equipe 1` VARCHAR(45) NULL,
  `Equipe 2` VARCHAR(45) NULL,
  `Equipe 3` VARCHAR(45) NULL,
  `Equipe 4` VARCHAR(45) NULL,
  `Equipe 5` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Ano` CHAR(4) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Equipes_idEquipes` INT NOT NULL,
  PRIMARY KEY (`idVeículo`),
  INDEX `fk_Veículo_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Veículo_Equipes1_idx` (`Equipes_idEquipes` ASC),
  CONSTRAINT `fk_Veículo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veículo_Equipes1`
    FOREIGN KEY (`Equipes_idEquipes`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Número` INT NULL,
  `Data de Emissão` DATETIME NULL,
  `Valor` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Data Conclusão` DATETIME NULL,
  `OS Autorizada` CHAR(1) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Veículo_idVeículo` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`),
  INDEX `fk_Ordem de Serviço_Equipe1_idx` (`Equipe_idEquipe` ASC),
  INDEX `fk_Ordem de Serviço_Veículo1_idx` (`Veículo_idVeículo` ASC),
  INDEX `fk_Ordem de Serviço_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Ordem de Serviço_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Revisão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Revisão` (
  `idRevisão` INT NOT NULL,
  `Serviço 1` VARCHAR(45) NULL,
  `Serviço 2` VARCHAR(45) NULL,
  `Serviço 3` VARCHAR(45) NULL,
  `Serviço 4` VARCHAR(45) NULL,
  `Serviço 5` VARCHAR(45) NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`idRevisão`),
  INDEX `fk_Revisão_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC),
  CONSTRAINT `fk_Revisão_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conserto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conserto` (
  `idConserto` INT NOT NULL,
  `Peça 1` VARCHAR(45) NULL,
  `Peça 2` VARCHAR(45) NULL,
  `Peça 3` VARCHAR(45) NULL,
  `Peça 4` VARCHAR(45) NULL,
  `Peça 5` VARCHAR(45) NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`idConserto`),
  INDEX `fk_Conserto_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC),
  CONSTRAINT `fk_Conserto_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Referência Mão de Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Referência Mão de Obra` (
  `idReferência Mão de Obra` INT NOT NULL,
  `Mão de Obra 1` VARCHAR(45) NULL,
  `Mão de Obra 2` VARCHAR(45) NULL,
  `Mão de obra 3` VARCHAR(45) NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`idReferência Mão de Obra`),
  INDEX `fk_Referência Mão de Obra_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC),
  CONSTRAINT `fk_Referência Mão de Obra_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânicos` (
  `idMecânicos` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Código` INT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idMecânicos`),
  INDEX `fk_Mecânicos_Equipe1_idx` (`Equipe_idEquipe` ASC),
  CONSTRAINT `fk_Mecânicos_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidade Mecânica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidade Mecânica` (
  `idEspecialidade Mecânica` INT NOT NULL,
  `Especialidade 1` VARCHAR(45) NULL,
  `Especialidade 2` VARCHAR(45) NULL,
  `Especialidade 3` VARCHAR(45) NULL,
  `Especialidade 4` VARCHAR(45) NULL,
  `Especialidade 5` VARCHAR(45) NULL,
  `Mecânicos_idMecânicos` INT NOT NULL,
  PRIMARY KEY (`idEspecialidade Mecânica`),
  INDEX `fk_Especialidade Mecânica_Mecânicos1_idx` (`Mecânicos_idMecânicos` ASC),
  CONSTRAINT `fk_Especialidade Mecânica_Mecânicos1`
    FOREIGN KEY (`Mecânicos_idMecânicos`)
    REFERENCES `mydb`.`Mecânicos` (`idMecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
